"""配置常量。"""

from __future__ import annotations


LIST_PAGE_SIZE = 50
MAX_VISIBLE_PAGES = 20
MAX_LEAF_RECORDS = LIST_PAGE_SIZE * MAX_VISIBLE_PAGES
DEFAULT_DETAIL_CONCURRENCY = 8
DEFAULT_GMAP_CONCURRENCY = 32
DEFAULT_SNOV_CONCURRENCY = 6
DEFAULT_ENRICH_POLL_INTERVAL = 10
DEFAULT_GMAP_BATCH_SIZE = 100
DEFAULT_SNOV_BATCH_SIZE = 200
