"""Italy DNB 分类切片。"""

from __future__ import annotations


# 直接复用已验证的 legacy subcategory slug，先保证 Italy DNB 能跑通。
LEGACY_SUBCATEGORY_SLUGS = [
    "accommodation_and_food_services",
    "accounting_tax_preparation_bookkeeping_and_payroll_services",
    "activities_related_to_credit_intermediation",
    "activities_related_to_real_estate",
    "administration_of_economic_programs",
    "administration_of_human_resource_programs",
    "administrative_and_support_and_waste_management_and_remediation_services",
    "advertising_public_relations_and_related_services",
    "aerospace_product_and_parts_manufacturing",
    "agencies_brokerages_and_other_insurance_related_activities",
    "agents_and_managers_for_artists_athletes_entertainers_and_other_public_figures",
    "agriculture_construction_and_mining_machinery_manufacturing",
    "agriculture_forestry_fishing_and_hunting",
    "all_other_telecommunications",
    "alumina_and_aluminum_production_and_processing",
    "amusement_parks_and_arcades",
    "animal_food_manufacturing",
    "animal_slaughtering_and_processing",
    "apparel_accessories_and_other_apparel_manufacturing",
    "apparel_knitting_mills",
    "apparel_piece_goods_and_notions_merchant_wholesalers",
    "aquaculture",
    "architectural_and_structural_metals_manufacturing",
    "architectural_engineering_and_related_services",
    "arts_entertainment_and_recreation",
    "audio_and_video_equipment_manufacturing",
    "automobile_dealers",
    "automotive_equipment_rental_and_leasing",
    "automotive_parts_accessories_and_tire_retailers",
    "automotive_repair_and_maintenance",
    "bakeries_and_tortilla_manufacturing",
    "basic_chemical_manufacturing",
    "beer_wine_and_distilled_alcoholic_beverage_merchant_wholesalers",
    "beer_wine_and_liquor_retailers",
    "beverage_manufacturing",
    "boiler_tank_and_shipping_container_manufacturing",
    "book_retailers_and_news_dealers",
    "building_equipment_contractors",
    "building_finishing_contractors",
    "building_material_and_supplies_dealers",
    "business_professional_labor_political_and_similar_organizations",
    "business_support_services",
    "cattle_ranching_and_farming",
    "cement_and_concrete_product_manufacturing",
    "chemical_and_allied_products_merchant_wholesalers",
    "child_care_services",
    "clay_product_and_refractory_manufacturing",
    "clothing_and_clothing_accessories_retailers",
    "coal_mining",
    "coating_engraving_heat_treating_and_allied_activities",
    "colleges_universities_and_professional_schools",
    "commercial_and_industrial_machinery_and_equipment_(except_automotive_and_electronic)_repair_and_maintenance",
    "commercial_and_industrial_machinery_and_equipment_rental_and_leasing",
    "commercial_and_service_industry_machinery_manufacturing",
    "communications_equipment_manufacturing",
    "computer_and_peripheral_equipment_manufacturing",
    "computer_systems_design_and_related_services",
    "computing_infrastructure_providers_data_processing_web_hosting_and_related_services",
    "construction",
    "consumer_goods_rental",
    "converted_paper_product_manufacturing",
    "couriers_and_express_delivery_services",
    "cut_and_sew_apparel_manufacturing",
    "cutlery_and_handtool_manufacturing",
    "dairy_product_manufacturing",
    "death_care_services",
    "deep_sea_coastal_and_great_lakes_water_transportation",
    "depository_credit_intermediation",
    "drinking_places_(alcoholic_beverages)",
    "drugs_and_druggists_sundries_merchant_wholesalers",
    "educational_services",
    "educational_support_services",
    "electric_lighting_equipment_manufacturing",
    "electric_power_generation_transmission_and_distribution",
    "electrical_equipment_manufacturing",
    "electronic_and_precision_equipment_repair_and_maintenance",
    "electronics_and_appliance_retailers",
    "elementary_and_secondary_schools",
    "employment_services",
    "engine_turbine_and_power_transmission_equipment_manufacturing",
    "executive_legislative_and_other_general_government_support",
    "fabric_mills",
    "farm_product_raw_material_merchant_wholesalers",
    "fiber_yarn_and_thread_mills",
    "finance_and_insurance",
    "fishing",
    "footwear_manufacturing",
    "forest_nurseries_and_gathering_of_forest_products",
    "forging_and_stamping",
    "foundation_structure_and_building_exterior_contractors",
    "foundries",
    "fruit_and_tree_nut_farming",
    "fruit_and_vegetable_preserving_and_specialty_food_manufacturing",
    "furniture_and_home_furnishing_merchant_wholesalers",
    "furniture_and_home_furnishings_retailers",
    "gambling_industries",
    "gasoline_stations",
    "general_freight_trucking",
    "general_medical_and_surgical_hospitals",
    "glass_and_glass_product_manufacturing",
    "grain_and_oilseed_milling",
    "greenhouse_nursery_and_floriculture_production",
    "grocery_and_convenience_retailers",
    "grocery_and_related_product_merchant_wholesalers",
    "hardware_and_plumbing_and_heating_equipment_and_supplies_merchant_wholesalers",
    "hardware_manufacturing",
    "health_and_personal_care_retailers",
    "health_care_and_social_assistance",
    "highway_street_and_bridge_construction",
    "hog_and_pig_farming",
    "household_and_institutional_furniture_and_kitchen_cabinet_manufacturing",
    "household_appliance_manufacturing",
    "household_appliances_and_electrical_and_electronic_goods_merchant_wholesalers",
    "hunting_and_trapping",
    "independent_artists_writers_and_performers",
    "individual_and_family_services",
    "industrial_machinery_manufacturing",
    "information",
    "inland_water_transportation",
    "insurance_and_employee_benefit_funds",
    "insurance_carriers",
    "investigation_and_security_services",
    "iron_and_steel_mills_and_ferroalloy_manufacturing",
    "jewelry_luggage_and_leather_goods_retailers",
    "justice_public_order_and_safety_activities",
    "land_subdivision",
    "leather_and_hide_tanning_and_finishing",
    "legal_services",
    "lessors_of_nonfinancial_intangible_assets_(except_copyrighted_works)",
    "lessors_of_real_estate",
    "lime_and_gypsum_product_manufacturing",
    "logging",
    "lumber_and_other_construction_materials_merchant_wholesalers",
    "machine_shops_turned_product_and_screw_nut_and_bolt_manufacturing",
    "machinery_equipment_and_supplies_merchant_wholesalers",
    "management_of_companies_and_enterprises",
    "management_scientific_and_technical_consulting_services",
    "manufacturing",
    "manufacturing_and_reproducing_magnetic_and_optical_media",
    "media_streaming_distribution_services_social_networks_and_other_media_networks_and_content_providers",
    "medical_equipment_and_supplies_manufacturing",
    "metal_and_mineral_(except_petroleum)_merchant_wholesalers",
    "metal_ore_mining",
    "metalworking_machinery_manufacturing",
    "mining_quarrying_and_oil_and_gas_extraction",
    "miscellaneous_durable_goods_merchant_wholesalers",
    "miscellaneous_nondurable_goods_merchant_wholesalers",
    "monetary_authorities-central_bank",
    "motion_picture_and_video_industries",
    "motor_vehicle_and_motor_vehicle_parts_and_supplies_merchant_wholesalers",
    "motor_vehicle_body_and_trailer_manufacturing",
    "motor_vehicle_manufacturing",
    "motor_vehicle_parts_manufacturing",
    "museums_historical_sites_and_similar_institutions",
    "national_security_and_international_affairs",
    "natural_gas_distribution",
    "navigational_measuring_electromedical_and_control_instruments_manufacturing",
    "newspaper_periodical_book_and_directory_publishers",
    "nondepository_credit_intermediation",
    "nonferrous_metal_(except_aluminum)_production_and_processing",
    "nonmetallic_mineral_mining_and_quarrying",
    "nonresidential_building_construction",
    "nonscheduled_air_transportation",
    "nursing_care_facilities_(skilled_nursing_facilities)",
    "office_administrative_services",
    "offices_of_dentists",
    "offices_of_other_health_practitioners",
    "offices_of_physicians",
    "offices_of_real_estate_agents_and_brokers",
    "oil_and_gas_extraction",
    "oilseed_and_grain_farming",
    "other_ambulatory_health_care_services",
    "other_amusement_and_recreation_industries",
    "other_animal_production",
    "other_chemical_product_and_preparation_manufacturing",
    "other_crop_farming",
    "other_electrical_equipment_and_component_manufacturing",
    "other_fabricated_metal_product_manufacturing",
    "other_financial_investment_activities",
    "other_food_manufacturing",
    "other_furniture_related_product_manufacturing",
    "other_general_purpose_machinery_manufacturing",
    "other_heavy_and_civil_engineering_construction",
    "other_investment_pools_and_funds",
    "other_leather_and_allied_product_manufacturing",
    "other_miscellaneous_manufacturing",
    "other_miscellaneous_retailers",
    "other_motor_vehicle_dealers",
    "other_nonmetallic_mineral_product_manufacturing",
    "other_personal_services",
    "other_pipeline_transportation",
    "other_professional_scientific_and_technical_services",
    "other_schools_and_instruction",
    "other_store_retailers",
    "other_support_activities_for_transportation",
    "other_telecommunications",
    "paper_and_paper_product_merchant_wholesalers",
    "paper_manufacturing",
    "performing_arts_companies",
    "personal_and_household_goods_repair_and_maintenance",
    "personal_care_services",
    "petroleum_and_coal_products_manufacturing",
    "petroleum_and_petroleum_products_merchant_wholesalers",
    "pharmaceutical_and_medicine_manufacturing",
    "pharmacy_and_drug_retailers",
    "plastics_product_manufacturing",
    "postal_service",
    "primary_metal_manufacturing",
    "printing_and_related_support_activities",
    "private_households",
    "professional_scientific_and_technical_services",
    "promoters_of_performing_arts_sports_and_similar_events",
    "publishing_industries_(except_internet)",
    "pulp_paper_and_paperboard_mills",
    "rail_transportation",
    "real_estate",
    "real_estate_and_rental_and_leasing",
    "religious_grantmaking_civic_professional_and_similar_organizations",
    "remediation_and_other_waste_management_services",
    "rental_and_leasing_services",
    "repair_and_maintenance",
    "residential_building_construction",
    "retail_trade",
    "scenic_and_sightseeing_transportation",
    "scientific_research_and_development_services",
    "securities_commodity_contracts_and_other_financial_investments_and_related_activities",
    "securities_and_commodity_contracts_intermediation_and_brokerage",
    "self-employed_workers",
    "ship_and_boat_building",
    "social_assistance",
    "specialized_design_services",
    "specialty_trade_contractors",
    "sporting_goods_hobby_musical_instrument_book_and_miscellaneous_retailers",
    "support_activities_for_agriculture_and_forestry",
    "support_activities_for_mining",
    "support_activities_for_transportation",
    "telecommunications",
    "textile_furnishings_mills",
    "textile_product_mills",
    "textile_mills",
    "transit_and_ground_passenger_transportation",
    "transportation_and_warehousing",
    "truck_transportation",
    "utilities",
    "warehousing_and_storage",
    "waste_collection",
    "waste_management_and_remediation_services",
    "water_transportation",
    "wholesale_electronic_markets_and_agents_and_brokers",
    "wholesale_trade",
    "wood_product_manufacturing",
    "wired_and_wireless_telecommunications_(except_satellite)",
]


def build_initial_segments(
    limit: int = 0,
    industry_paths: list[str] | tuple[str, ...] | None = None,
) -> list[dict[str, str | int]]:
    """生成 Italy DNB 初始切片。"""
    if industry_paths:
        requested = [str(item or "").strip() for item in industry_paths if str(item or "").strip()]
        items = [slug for slug in LEGACY_SUBCATEGORY_SLUGS if slug in requested]
    else:
        items = LEGACY_SUBCATEGORY_SLUGS[: max(int(limit or 0), 0)] if int(limit or 0) > 0 else LEGACY_SUBCATEGORY_SLUGS
    return [
        {
            "segment_id": f"{industry_path}|it||",
            "segment_type": "subcategory",
            "industry_path": industry_path,
            "country_iso_two_code": "it",
            "region_name": "",
            "city_name": "",
            "expected_count": 0,
            "next_page": 1,
            "status": "pending",
        }
        for industry_path in items
    ]
